#ifndef ORE_EVENT_MANAGER__H_
#define ORE_EVENT_MANAGER__H_

#include "Define.h"
#include "Event.hpp"
#include "Ore.h"

#include <GLFW/glfw3.h>

namespace Ore
{
	enum class GamepadId
	{
		GAMEPAD_1,
		GAMEPAD_2,
		GAMEPAD_3,
		GAMEPAD_4,
		GAMEPAD_5,
		GAMEPAD_6,
		GAMEPAD_7,
		GAMEPAD_8,
		GAMEPAD_9,
		GAMEPAD_10,
		GAMEPAD_11,
		GAMEPAD_12,
		GAMEPAD_13,
		GAMEPAD_14,
		GAMEPAD_15,
		GAMEPAD_16,

		GAMEPAD_MAX
	};

	enum class EventInput
	{
		KEY_A = GLFW_KEY_A,
		KEY_M = GLFW_KEY_M,
		KEY_SEMICOLON = GLFW_KEY_SEMICOLON,
		KEY_COMMA = GLFW_KEY_COMMA,
		KEY_Q = GLFW_KEY_Q,
		KEY_W = GLFW_KEY_W,
		KEY_Z = GLFW_KEY_Z,

		KEY_B = GLFW_KEY_B,
		KEY_C = GLFW_KEY_C,
		KEY_D = GLFW_KEY_D,
		KEY_E = GLFW_KEY_E,
		KEY_F = GLFW_KEY_F,
		KEY_G = GLFW_KEY_G,
		KEY_H = GLFW_KEY_H,
		KEY_I = GLFW_KEY_I,
		KEY_J = GLFW_KEY_J,
		KEY_K = GLFW_KEY_K,
		KEY_L = GLFW_KEY_L,
		KEY_N = GLFW_KEY_N,
		KEY_O = GLFW_KEY_O,
		KEY_P = GLFW_KEY_P,
		KEY_R = GLFW_KEY_R,
		KEY_S = GLFW_KEY_S,
		KEY_T = GLFW_KEY_T,
		KEY_U = GLFW_KEY_U,
		KEY_V = GLFW_KEY_V,
		KEY_X = GLFW_KEY_X,
		KEY_Y = GLFW_KEY_Y,
		KEY_0 = GLFW_KEY_0,
		KEY_1 = GLFW_KEY_1,
		KEY_2 = GLFW_KEY_2,
		KEY_3 = GLFW_KEY_3,
		KEY_4 = GLFW_KEY_4,
		KEY_5 = GLFW_KEY_5,
		KEY_6 = GLFW_KEY_6,
		KEY_7 = GLFW_KEY_7,
		KEY_8 = GLFW_KEY_8,
		KEY_9 = GLFW_KEY_9,
		KEY_APOSTROPHE = GLFW_KEY_APOSTROPHE,
		KEY_MINUS = GLFW_KEY_MINUS,
		KEY_PERIOD = GLFW_KEY_PERIOD,
		KEY_SLASH = GLFW_KEY_SLASH,
		KEY_EQUAL = GLFW_KEY_EQUAL,
		KEY_ESCAPE = GLFW_KEY_ESCAPE,
		KEY_SPACE = GLFW_KEY_SPACE,
		KEY_ENTER = GLFW_KEY_ENTER,
		KEY_TAB = GLFW_KEY_TAB,
		KEY_BACKSPACE = GLFW_KEY_BACKSPACE,
		KEY_INSERT = GLFW_KEY_INSERT,
		KEY_DELETE = GLFW_KEY_DELETE,
		KEY_RIGHT = GLFW_KEY_RIGHT,
		KEY_LEFT = GLFW_KEY_LEFT,
		KEY_DOWN = GLFW_KEY_DOWN,
		KEY_UP = GLFW_KEY_UP,
		KEY_PAGE_UP = GLFW_KEY_PAGE_UP,
		KEY_PAGE_DOWN = GLFW_KEY_PAGE_DOWN,
		KEY_HOME = GLFW_KEY_HOME,
		KEY_END = GLFW_KEY_END,
		KEY_CAPS_LOCK = GLFW_KEY_CAPS_LOCK,
		KEY_SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK,
		KEY_NUM_LOCK = GLFW_KEY_NUM_LOCK,
		KEY_PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN,
		KEY_PAUSE = GLFW_KEY_PAUSE,
		KEY_SHIFT = GLFW_KEY_RIGHT_SHIFT,
		KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
		KEY_CTRL = GLFW_KEY_RIGHT_CONTROL,
		KEY_LEFT_CTRL = GLFW_KEY_LEFT_CONTROL,
		KEY_ALT = GLFW_KEY_RIGHT_ALT,
		KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT,
		KEY_SUPER = GLFW_KEY_RIGHT_SUPER,
		KEY_LEFT_SUPER = GLFW_KEY_LEFT_SUPER,
		KEY_MENU = GLFW_KEY_MENU,
		KEY_F1 = GLFW_KEY_F1,
		KEY_F2 = GLFW_KEY_F2,
		KEY_F3 = GLFW_KEY_F3,
		KEY_F4 = GLFW_KEY_F4,
		KEY_F5 = GLFW_KEY_F5,
		KEY_F6 = GLFW_KEY_F6,
		KEY_F7 = GLFW_KEY_F7,
		KEY_F8 = GLFW_KEY_F8,
		KEY_F9 = GLFW_KEY_F9,
		KEY_F10 = GLFW_KEY_F10,
		KEY_F11 = GLFW_KEY_F11,
		KEY_F12 = GLFW_KEY_F12,
		KEY_F13 = GLFW_KEY_F13,
		KEY_F14 = GLFW_KEY_F14,
		KEY_F15 = GLFW_KEY_F15,
		KEY_F16 = GLFW_KEY_F16,
		KEY_F17 = GLFW_KEY_F17,
		KEY_F18 = GLFW_KEY_F18,
		KEY_F19 = GLFW_KEY_F19,
		KEY_F20 = GLFW_KEY_F20,
		KEY_F21 = GLFW_KEY_F21,
		KEY_F22 = GLFW_KEY_F22,
		KEY_F23 = GLFW_KEY_F23,
		KEY_F24 = GLFW_KEY_F24,
		KEY_F25 = GLFW_KEY_F25,
		KEY_KP_0 = GLFW_KEY_KP_0,
		KEY_KP_1 = GLFW_KEY_KP_1,
		KEY_KP_2 = GLFW_KEY_KP_2,
		KEY_KP_3 = GLFW_KEY_KP_3,
		KEY_KP_4 = GLFW_KEY_KP_4,
		KEY_KP_5 = GLFW_KEY_KP_5,
		KEY_KP_6 = GLFW_KEY_KP_6,
		KEY_KP_7 = GLFW_KEY_KP_7,
		KEY_KP_8 = GLFW_KEY_KP_8,
		KEY_KP_9 = GLFW_KEY_KP_9,
		KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL,
		KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE,
		KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY,
		KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
		KEY_KP_ADD = GLFW_KEY_KP_ADD,
		KEY_KP_ENTER = GLFW_KEY_KP_ENTER,
		KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL,

		MOUSE_LEFT = GLFW_MOUSE_BUTTON_LEFT,
		MOUSE_RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
		MOUSE_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE,
		MOUSE_X1 = GLFW_MOUSE_BUTTON_1,
		MOUSE_X2 = GLFW_MOUSE_BUTTON_2,
		MOUSE_MOVE = 0xff0,

		GAMEPAD_A = GLFW_GAMEPAD_BUTTON_A,
		GAMEPAD_B = GLFW_GAMEPAD_BUTTON_B,
		GAMEPAD_X = GLFW_GAMEPAD_BUTTON_X,
		GAMEPAD_Y = GLFW_GAMEPAD_BUTTON_Y,
		GAMEPAD_LEFT_BUMPER = GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
		GAMEPAD_RIGHT_BUMPER = GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
		GAMEPAD_BACK = GLFW_GAMEPAD_BUTTON_BACK,
		GAMEPAD_START = GLFW_GAMEPAD_BUTTON_START,
		GAMEPAD_GUIDE = GLFW_GAMEPAD_BUTTON_GUIDE,
		GAMEPAD_LEFT_STICK = GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
		GAMEPAD_RIGHT_STICK = GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
		GAMEPAD_DPAD_UP = GLFW_GAMEPAD_BUTTON_DPAD_UP,
		GAMEPAD_DPAD_RIGHT = GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
		GAMEPAD_DPAD_DOWN = GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
		GAMEPAD_DPAD_LEFT = GLFW_GAMEPAD_BUTTON_DPAD_LEFT,

		GAMEPAD_LEFT_TRIGGER = GLFW_GAMEPAD_AXIS_LEFT_TRIGGER,
		GAMEPAD_RIGHT_TRIGGER = GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER,
		GAMEPAD_LEFT_X = GLFW_GAMEPAD_AXIS_LEFT_X,
		GAMEPAD_LEFT_Y = GLFW_GAMEPAD_AXIS_LEFT_Y,
		GAMEPAD_RIGHT_X = GLFW_GAMEPAD_AXIS_RIGHT_X,
		GAMEPAD_RIGHT_Y = GLFW_GAMEPAD_AXIS_RIGHT_Y,
	};

	enum class EventAction
	{
		PRESS = GLFW_PRESS,
		RELEASE = GLFW_RELEASE,
		HOLD,
		DOUBLE_CLICK,
		WHEEL_UP,
		WHEEL_DOWN,
		MOVE,
		DRAG,
		FOCUS,
		BLUR,
		CHANGE,
		UNKNOWN
	};

	ENUM_CLASS_FLAGS(GamepadId)
	ENUM_CLASS_FLAGS(EventInput)
	ENUM_CLASS_FLAGS(EventAction)

	class EventManager
	{
	public:
		static void GetKeyCallback(GLFWwindow* window, int key, int scancode, int action, int mods);
		static void GetMouseButtonCallBack(GLFWwindow* window, int button, int action, int mods);
		static void GetCursorPosCallBack(GLFWwindow* window, double xpos, double ypos);

		static bool CheckGamepad(GamepadId id);
		static void JoystickCallback(int jId, int event);
		static std::string_view GetGamepadName(GamepadId id);
		static float GetGamepadAxes(GamepadId id, EventInput button);
		static bool GetButton(GamepadId id, EventInput button);

		inline static Event<void(GamepadId)> gamepadConnected = Event<void(GamepadId)>();
		inline static Event<void(GamepadId)> gamepadDisconnected = Event<void(GamepadId)>();

		inline static Event<void(EventInput, EventAction)> getKey = Event<void(EventInput, EventAction)>();
		inline static Event<void(EventInput, EventAction)> getMouse = Event<void(EventInput, EventAction)>();
		inline static Event<void(float, float)> getCursorPos = Event<void(float, float)>();
	};
}

#endif // !ORE_EVENT_MANAGER__H_
